[package]
name = "tetan_os"
version = "0.1.0"
description = "An attempt at building an operating system, make sure you're vaxxed."
authors = ["Alexandre Frigon <alexandre.frigon.1@gmail.com>"]
edition = "2018"

documentation = ""
homepage = ""
repository = "https://github.com/afrigon/TetanOS"
readme = "https://github.com/afrigon/TetanOS/blob/master/README.md"
license-file = "https://github.com/afrigon/TetanOS/blob/master/LICENSE"
keywords = ["Operating", "system", "tetanus", "tetanos", "vaxx"]
categories = ["no-std"]

[badges]
travis-ci = { repository = "https://github.com/afrigon/TetanOS", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
bootloader = "^0.3.12"
spin = "0.4.9"
volatile = "0.2.3"
uart_16550 = "0.1.0"

[package.metadata.bootimage]
default-target = "x86_64.json"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
